### ISSUE TITLE
Fractional final segments are not calculated in WLC

### ISSUE THREAD

**Issue by kmdouglass** [MStefko/PolymerCpp#2]
Unlike in the original Python code, any fractional final segment of the chain is dropped and simply not computed. (See line 38 of **WLC.cpp**.)

This is only a minor bug that I can fix in the near future.

**Comment by MStefko** [comment]
```C++
// no leftover for the time being
```

Well, at least I was nice enough to mention it. Also, quite clairvoyant of me to see it would be eventually fixed two years into the future haha.

**Comment by kmdouglass** [comment]
Actually, this is no longer a bug after the project restructuring. All chains are now discrete walks with segments of unit length. See #3 for more information.
