### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by chrisclarkson100** [MStefko/PolymerCpp#9]
I have attempted 'pip install PolymerCpp' on two different computers- one a mac osx and another a linux. I have updated pip to the latest versions on both but this same error results in both cases....

Collecting PolymerCpp
  Downloading PolymerCpp-0.1.3.tar.gz (834kB)
    100% |████████████████████████████████| 839kB 1.4MB/s 
Requirement already satisfied: numpy>=1.11.0 in ./anaconda2/lib/python2.7/site-packages (from PolymerCpp)
Requirement already satisfied: matplotlib>=2.0.0 in ./anaconda2/lib/python2.7/site-packages (from PolymerCpp)
Requirement already satisfied: six>=1.10 in ./anaconda2/lib/python2.7/site-packages (from matplotlib>=2.0.0->PolymerCpp)
Requirement already satisfied: python-dateutil in ./anaconda2/lib/python2.7/site-packages (from matplotlib>=2.0.0->PolymerCpp)
Requirement already satisfied: functools32 in ./anaconda2/lib/python2.7/site-packages (from matplotlib>=2.0.0->PolymerCpp)
Requirement already satisfied: subprocess32 in ./anaconda2/lib/python2.7/site-packages (from matplotlib>=2.0.0->PolymerCpp)
Requirement already satisfied: pytz in ./anaconda2/lib/python2.7/site-packages (from matplotlib>=2.0.0->PolymerCpp)
Requirement already satisfied: cycler>=0.10 in ./anaconda2/lib/python2.7/site-packages (from matplotlib>=2.0.0->PolymerCpp)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in ./anaconda2/lib/python2.7/site-packages (from matplotlib>=2.0.0->PolymerCpp)
Building wheels for collected packages: PolymerCpp
  Running setup.py bdist_wheel for PolymerCpp ... error
  Complete output from command /home/bsxcto/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wwU6PY/PolymerCpp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpyHOQsJpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/PolymerCpp
  copying PolymerCpp/helpers.py -> build/lib.linux-x86_64-2.7/PolymerCpp
  copying PolymerCpp/__init__.py -> build/lib.linux-x86_64-2.7/PolymerCpp
  copying PolymerCpp/algorithms.py -> build/lib.linux-x86_64-2.7/PolymerCpp
  running build_ext
  building 'PolymerCppCore' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/PolymerCpp
  creating build/temp.linux-x86_64-2.7/PolymerCpp/core
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Iinclude -I/home/bsxcto/anaconda2/include/python2.7 -c PolymerCpp/core/Misc.cpp -o build/temp.linux-x86_64-2.7/PolymerCpp/core/Misc.o -std=c++11 -O2 -fPIC
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  PolymerCpp/core/Misc.cpp: In function ‘void convSegments(std::vector<double>&, std::vector<double>&, double, bool)’:
  PolymerCpp/core/Misc.cpp:29:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int i=0; i<inVector.size(); i++)
                                     ^
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Iinclude -I/home/bsxcto/anaconda2/include/python2.7 -c PolymerCpp/core/RgDict.cpp -o build/temp.linux-x86_64-2.7/PolymerCpp/core/RgDict.o -std=c++11 -O2 -fPIC
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  PolymerCpp/core/RgDict.cpp: In member function ‘void RgDict::addToDBfileFull(std::ofstream&)’:
  PolymerCpp/core/RgDict.cpp:44:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int i=0; i<Rg.size(); i++)
                               ^
  PolymerCpp/core/RgDict.cpp:49:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int i=0; i<Rg.size(); i++)
                               ^
  PolymerCpp/core/RgDict.cpp: In member function ‘void RgDict::addToDBfileShort(std::ofstream&)’:
  PolymerCpp/core/RgDict.cpp:65:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int i=0; i<Rg.size(); i++)
                               ^
  PolymerCpp/core/RgDict.cpp:74:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int i=0; i<Rg.size(); i++)
                               ^
  PolymerCpp/core/RgDict.cpp: In member function ‘double RgDict::getVariance(bool)’:
  PolymerCpp/core/RgDict.cpp:93:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int i=0; i<RgPtr->size(); i++)
                                   ^
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Iinclude -I/home/bsxcto/anaconda2/include/python2.7 -c PolymerCpp/core/Stopwatch.cpp -o build/temp.linux-x86_64-2.7/PolymerCpp/core/Stopwatch.o -std=c++11 -O2 -fPIC
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from PolymerCpp/core/Stopwatch.cpp:36:0:
  include/Stopwatch.h: In constructor ‘Stopwatch::Stopwatch()’:
  include/Stopwatch.h:241:14: warning: ‘Stopwatch::active’ will be initialized after [-Wreorder]
           bool active;
                ^
  include/Stopwatch.h:235:23: warning:   ‘StopwatchMode Stopwatch::mode’ [-Wreorder]
           StopwatchMode mode;
                         ^
  PolymerCpp/core/Stopwatch.cpp:42:1: warning:   when initialized here [-Wreorder]
   Stopwatch::Stopwatch() : active(true), mode(NONE)  {
   ^
  PolymerCpp/core/Stopwatch.cpp: In member function ‘void Stopwatch::report(std::string, std::ostream&)’:
  PolymerCpp/core/Stopwatch.cpp:232:46: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           for (int i = 0; i < perf_name.length(); i++)
                                                ^
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Iinclude -I/home/bsxcto/anaconda2/include/python2.7 -c PolymerCpp/core/PolymerCpp.cpp -o build/temp.linux-x86_64-2.7/PolymerCpp/core/PolymerCpp.o -std=c++11 -O2 -fPIC
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  PolymerCpp/core/PolymerCpp.cpp: In function ‘PyObject* getWLCrgs(PyObject*, PyObject*)’:
  PolymerCpp/core/PolymerCpp.cpp:46:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (unsigned int i=0; i<numPaths; i++)
                                ^
  PolymerCpp/core/PolymerCpp.cpp: In function ‘PyObject* getSAWLCrgs(PyObject*, PyObject*)’:
  PolymerCpp/core/PolymerCpp.cpp:144:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (unsigned int i=0; i < numPaths; i++)
                                  ^
  PolymerCpp/core/PolymerCpp.cpp: At global scope:
  PolymerCpp/core/PolymerCpp.cpp:202:27: error: variable ‘PyModuleDef PolymerCppCore’ has initializer but incomplete type
   static struct PyModuleDef PolymerCppCore =
                             ^
  PolymerCpp/core/PolymerCpp.cpp:204:5: error: ‘PyModuleDef_HEAD_INIT’ was not declared in this scope
       PyModuleDef_HEAD_INIT,
       ^
  PolymerCpp/core/PolymerCpp.cpp: In function ‘void PyInit_PolymerCppCore()’:
  PolymerCpp/core/PolymerCpp.cpp:214:41: error: ‘PyModule_Create’ was not declared in this scope
     return PyModule_Create(&PolymerCppCore);
                                           ^
  PolymerCpp/core/PolymerCpp.cpp:214:41: error: return-statement with a value, in function returning 'void' [-fpermissive]
  PolymerCpp/core/PolymerCpp.cpp: In function ‘int main(int, char**)’:
  PolymerCpp/core/PolymerCpp.cpp:219:53: error: ‘Py_DecodeLocale’ was not declared in this scope
       wchar_t *program = Py_DecodeLocale(argv[0], NULL);
                                                       ^
  PolymerCpp/core/PolymerCpp.cpp:229:30: error: cannot convert ‘wchar_t*’ to ‘char*’ for argument ‘1’ to ‘void Py_SetProgramName(char*)’
       Py_SetProgramName(program);
                                ^
  PolymerCpp/core/PolymerCpp.cpp:239:26: error: ‘PyMem_RawFree’ was not declared in this scope
       PyMem_RawFree(program);
                            ^
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for PolymerCpp
  Running setup.py clean for PolymerCpp
Failed to build PolymerCpp
Installing collected packages: PolymerCpp
  Running setup.py install for PolymerCpp ... error
    Complete output from command /home/bsxcto/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wwU6PY/PolymerCpp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dZUHb8-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/PolymerCpp
    copying PolymerCpp/helpers.py -> build/lib.linux-x86_64-2.7/PolymerCpp
    copying PolymerCpp/__init__.py -> build/lib.linux-x86_64-2.7/PolymerCpp
    copying PolymerCpp/algorithms.py -> build/lib.linux-x86_64-2.7/PolymerCpp
    running build_ext
    building 'PolymerCppCore' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/PolymerCpp
    creating build/temp.linux-x86_64-2.7/PolymerCpp/core
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Iinclude -I/home/bsxcto/anaconda2/include/python2.7 -c PolymerCpp/core/Misc.cpp -o build/temp.linux-x86_64-2.7/PolymerCpp/core/Misc.o -std=c++11 -O2 -fPIC
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    PolymerCpp/core/Misc.cpp: In function ‘void convSegments(std::vector<double>&, std::vector<double>&, double, bool)’:
    PolymerCpp/core/Misc.cpp:29:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i=0; i<inVector.size(); i++)
                                       ^
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Iinclude -I/home/bsxcto/anaconda2/include/python2.7 -c PolymerCpp/core/RgDict.cpp -o build/temp.linux-x86_64-2.7/PolymerCpp/core/RgDict.o -std=c++11 -O2 -fPIC
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    PolymerCpp/core/RgDict.cpp: In member function ‘void RgDict::addToDBfileFull(std::ofstream&)’:
    PolymerCpp/core/RgDict.cpp:44:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i=0; i<Rg.size(); i++)
                                 ^
    PolymerCpp/core/RgDict.cpp:49:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i=0; i<Rg.size(); i++)
                                 ^
    PolymerCpp/core/RgDict.cpp: In member function ‘void RgDict::addToDBfileShort(std::ofstream&)’:
    PolymerCpp/core/RgDict.cpp:65:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i=0; i<Rg.size(); i++)
                                 ^
    PolymerCpp/core/RgDict.cpp:74:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i=0; i<Rg.size(); i++)
                                 ^
    PolymerCpp/core/RgDict.cpp: In member function ‘double RgDict::getVariance(bool)’:
    PolymerCpp/core/RgDict.cpp:93:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i=0; i<RgPtr->size(); i++)
                                     ^
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Iinclude -I/home/bsxcto/anaconda2/include/python2.7 -c PolymerCpp/core/Stopwatch.cpp -o build/temp.linux-x86_64-2.7/PolymerCpp/core/Stopwatch.o -std=c++11 -O2 -fPIC
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from PolymerCpp/core/Stopwatch.cpp:36:0:
    include/Stopwatch.h: In constructor ‘Stopwatch::Stopwatch()’:
    include/Stopwatch.h:241:14: warning: ‘Stopwatch::active’ will be initialized after [-Wreorder]
             bool active;
                  ^
    include/Stopwatch.h:235:23: warning:   ‘StopwatchMode Stopwatch::mode’ [-Wreorder]
             StopwatchMode mode;
                           ^
    PolymerCpp/core/Stopwatch.cpp:42:1: warning:   when initialized here [-Wreorder]
     Stopwatch::Stopwatch() : active(true), mode(NONE)  {
     ^
    PolymerCpp/core/Stopwatch.cpp: In member function ‘void Stopwatch::report(std::string, std::ostream&)’:
    PolymerCpp/core/Stopwatch.cpp:232:46: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (int i = 0; i < perf_name.length(); i++)
                                                  ^
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Iinclude -I/home/bsxcto/anaconda2/include/python2.7 -c PolymerCpp/core/PolymerCpp.cpp -o build/temp.linux-x86_64-2.7/PolymerCpp/core/PolymerCpp.o -std=c++11 -O2 -fPIC
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    PolymerCpp/core/PolymerCpp.cpp: In function ‘PyObject* getWLCrgs(PyObject*, PyObject*)’:
    PolymerCpp/core/PolymerCpp.cpp:46:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (unsigned int i=0; i<numPaths; i++)
                                  ^
    PolymerCpp/core/PolymerCpp.cpp: In function ‘PyObject* getSAWLCrgs(PyObject*, PyObject*)’:
    PolymerCpp/core/PolymerCpp.cpp:144:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (unsigned int i=0; i < numPaths; i++)
                                    ^
    PolymerCpp/core/PolymerCpp.cpp: At global scope:
    PolymerCpp/core/PolymerCpp.cpp:202:27: error: variable ‘PyModuleDef PolymerCppCore’ has initializer but incomplete type
     static struct PyModuleDef PolymerCppCore =
                               ^
    PolymerCpp/core/PolymerCpp.cpp:204:5: error: ‘PyModuleDef_HEAD_INIT’ was not declared in this scope
         PyModuleDef_HEAD_INIT,
         ^
    PolymerCpp/core/PolymerCpp.cpp: In function ‘void PyInit_PolymerCppCore()’:
    PolymerCpp/core/PolymerCpp.cpp:214:41: error: ‘PyModule_Create’ was not declared in this scope
       return PyModule_Create(&PolymerCppCore);
                                             ^
    PolymerCpp/core/PolymerCpp.cpp:214:41: error: return-statement with a value, in function returning 'void' [-fpermissive]
    PolymerCpp/core/PolymerCpp.cpp: In function ‘int main(int, char**)’:
    PolymerCpp/core/PolymerCpp.cpp:219:53: error: ‘Py_DecodeLocale’ was not declared in this scope
         wchar_t *program = Py_DecodeLocale(argv[0], NULL);
                                                         ^
    PolymerCpp/core/PolymerCpp.cpp:229:30: error: cannot convert ‘wchar_t*’ to ‘char*’ for argument ‘1’ to ‘void Py_SetProgramName(char*)’
         Py_SetProgramName(program);
                                  ^
    PolymerCpp/core/PolymerCpp.cpp:239:26: error: ‘PyMem_RawFree’ was not declared in this scope
         PyMem_RawFree(program);
                              ^
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/bsxcto/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wwU6PY/PolymerCpp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dZUHb8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-wwU6PY/PolymerCpp/

**Comment by kmdouglass** [comment]
Hi Chris,
I'm looking at this on my phone, so I might be wrong, but it looks like
you're using Python 2.7. We wrote PolymerCpp for Python 3.

Give Python 3.5 a try and let me know how it goes.

**Comment by chrisclarkson** [comment]
Hi you were right thank you :)
